version: '3.8'

services:
  server:
    container_name: pokemon_api
    restart: always
    build:
      context: .
      args:
        - db_user=$DB_USER
        - db_name=$DB_NAME
        - db_password=$DB_PASSWORD
        - db_host=psql_db
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    depends_on:
      - psql_db
    networks:
      - backend
  
  psql_db:
    container_name: pokemon_db
    build:
      context: db/init
      dockerfile: Dockerfile
    restart: always
    environment:
      POSTGRES_USER: $DB_USER
      POSTGRES_PASSWORD: $DB_PASSWORD
      POSTGRES_DB: $DB_NAME
    ports:
      - '5432:5432'
    volumes:
      - db-data:/data/db
    networks:
      - backend

volumes:
  db-data:

networks:
  backend: